# 1주차

### 2 행렬의 덧셈

In [1]:
import numpy as np

def solution(arr1,arr2):
    return (np.array(arr1) + np.array(arr2)).tolist()



In [2]:
arr1 = [[1,2],[2,3]]
type(arr1)

list

In [3]:
# 첫 실수
# 함수 정의할 때 : 안씀.


# 두번째 실수
# np.array(리스트) 기억이 안남.. (np변환만 10번 넘게 검색한듯.. 이제는 기억할 때가 되지 않았는가)


# 세번째 실수
# 타입오류남. 오류코드는.....
# TypeError: Object of type ndarray is not JSON serializable
# 그대로 검색해보니 어레이.tolist() 붙이면 리스트로 변환 됨.

3 수박수박수박수박수박수?

In [4]:
def solution(n):
    몫 = n//2
    나머지 = n%2
    answer = ('수박')*몫 + ('수')*나머지
    return answer

In [5]:
solution(2000)

'수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수

4 완주하지 못한 선수

In [6]:
def solution(participant, completion):
    participant.sort()
    completion.sort()
    for i in range(len(completion)):
        if participant[i] == completion[i]:
            continue
        else:
            return participant[i]
    return participant[-1]

7 핸드폰 번호 가리기

In [7]:
#나의 코드

def solution(phone_number):
    return phone_number.replace(phone_number[:-4],'*'*(len(phone_number)-4))
    # 핸드폰번호를 대채하는데, 다른부분은 놔두고, 처음부터 -4번째 전까지만 바꾼다. 바꿀부분은 별로 바꿀껀데, 그 갯수는 원래 핸드폰 길이에서 4개 적은 개수로 한다.

In [8]:
#다른 사람 코드

def hide_numbers(s):
    return "*"*(len(s)-4) + s[-4:]

# 2주차

### 8 크레인 인형뽑기 게임

#### 1차시도 - 실패

In [9]:
import numpy as np

In [10]:
# board
# [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]

In [11]:
a=np.array([[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]])
a_trans = a.T

a

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 0, 3],
       [0, 2, 5, 0, 1],
       [4, 2, 4, 4, 2],
       [3, 5, 1, 3, 1]])

In [12]:
a_trans #전치행렬

array([[0, 0, 0, 4, 3],
       [0, 0, 2, 2, 5],
       [0, 1, 5, 4, 1],
       [0, 0, 0, 4, 3],
       [0, 3, 1, 2, 1]])

In [13]:
a_trans[0]

array([0, 0, 0, 4, 3])

In [14]:
a_trans[4]

array([0, 3, 1, 2, 1])

In [15]:
# def enter(moves):
#     for i in range(len(moves)):
#         h = k[i][0]
#         print(k[i])
#         print(h)
#     return

In [16]:
moves = [1,5,3,5,1,2,1,4] #a_trans 의 index 0,4,2,4,0,1,0,3 을 찾는다 

In [17]:
def 상준(move):
    a = []
    for i in range(len(move)):
        a.append(np.trim_zeros(a_trans[move[i]-1], trim='f')[0])
        # arr = np.delete(arr, 13) #사용한 변수를 지우는 작업을 해야하는데.ㅠ
    return a
        

In [18]:
# #함수를.. 만들 때... 변수명까지 같이 만들 수 있는가??!

# #생성할 변수 개수
# df_num=5

# #자동 변수 선언
# for i in range(1,df_num+1):
# 	globals()['df_{}'.format(i)]="hi~ df_{}".format(i)

# #선언 변수 출력
# for i in range(1,df_num+1):
# 	print(globals()['df_{}'.format(i)])

In [19]:
# i = 3
# moves[3]-1 #4
# a_trans[4] # array([0, 3, 1, 2, 1])
np.trim_zeros(([0, 3, 1, 2, 1]), trim='f') #[3, 1, 2, 1]
#원인을 찾았다.. 지워져야하는데.. 내 마음 속에서만 지웠구나..

[3, 1, 2, 1]

In [20]:
def ho():
    b = []
    for i in range(8):
        b.append(i)
    return b

ho()

# for i in range(10):
    # print(i)

[0, 1, 2, 3, 4, 5, 6, 7]

In [21]:
상준(moves)

[4, 3, 1, 3, 4, 2, 4, 4]

In [22]:
a_trans[상준(moves)]

array([[0, 3, 1, 2, 1],
       [0, 0, 0, 4, 3],
       [0, 0, 2, 2, 5],
       [0, 0, 0, 4, 3],
       [0, 3, 1, 2, 1],
       [0, 1, 5, 4, 1],
       [0, 3, 1, 2, 1],
       [0, 3, 1, 2, 1]])

In [23]:
# 배열의 13번째 값인 [70]을 삭제하기
# arr = np.delete(arr, 13) # axis 값을 입력하지 않아도 된다.
# arr

In [24]:
#moves [1,5,3,5,1,2,1,4]

In [25]:
a_trans_delete_0 = np.trim_zeros(a_trans[0], trim='f')
a_trans_delete_1 = np.trim_zeros(a_trans[1], trim='f')
a_trans_delete_2 = np.trim_zeros(a_trans[2], trim='f')
a_trans_delete_3 = np.trim_zeros(a_trans[3], trim='f')
a_trans_delete_4 = np.trim_zeros(a_trans[4], trim='f')

In [26]:
print(a_trans_delete_0)
print(a_trans_delete_1)
print(a_trans_delete_2)
print(a_trans_delete_3)
print(a_trans_delete_4) #결과값을 행렬로 다시 나타낼 수 있는가?

[4 3]
[2 2 5]
[1 5 4 1]
[4 3]
[3 1 2 1]


In [27]:
# np.concatenate((a_trans_delete_0,a_trans_delete_1),axis=2)

#### 2차 시도

In [28]:
import numpy as np

In [29]:
# board
# [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]

# moves = [1,5,3,5,1,2,1,4] #a_trans 의 index 0,4,2,4,0,1,0,3 을 찾는다 

In [30]:
board =np.array([[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]])
board_trans = board.T

In [31]:
a_trans

array([[0, 0, 0, 4, 3],
       [0, 0, 2, 2, 5],
       [0, 1, 5, 4, 1],
       [0, 0, 0, 4, 3],
       [0, 3, 1, 2, 1]])

In [32]:
# doll_pull(a_trans[0])

In [33]:
# #3일차 완성작

# def 상준(move):
#     a = []
#     for i in range(len(move)):
#         c = a_trans[move[i]-1]
#         try:
#             # print(np.trim_zeros(c, trim='f')[0])
#             a.append(np.trim_zeros(c, trim='f')[0])
#             # print(a)
#         except IndexError:
#             pass
#         doll_pull(c)
#     return a


# 상준(moves)
# #오........ ㅠㅠㅠㅠㅠㅠ 거의 나와버렸다. ㅠㅠㅠㅠㅠㅠㅠㅠ
# #이제 중복만 제거하면 된다.. ㅠㅠ

In [34]:
# def doll_pull(c):
#     for i in range(len(c)):
#         if c[i] != 0:
#             answer = c[i]
#             c[i] = 0
#             # print(a_trans)
#             return(answer)
#         else:
#             pass

# #완벽하다.. 내가 원하는 함수를 만들었따.. ㅠㅠ

In [35]:
import numpy as np

def doll_pull(c): #뽑는 기계, c=기계가 뽑을 행
    for i in range(len(c)): #c를 차례로 돌며 값이 있나 확인
        if c[i] != 0: # c안의 값이 0이 아니라면,
            answer = c[i]  #인형을 복사해서 정답에 넣고,
            c[i] = 0 #복사된 인형은 삭제 (0으로 바꾸기)
            print(answer) #(삭제없는) 정답함 확인
            return(answer)
        else:     #c안의 값이 0이라면..?
            pass  #그냥 넘어가


def solution(board, moves):
    board = np.array(board) #보드를 넘파이로
    b = board.T  #보드 전치
    a = []
    answer = 0
    for i in range(len(moves)): #moves 길이만큼 반복.. 뭘?
        c = b[moves[i]-1]  #moves에서 말하는 board 행 찾기
        try:
            t = np.trim_zeros(c, trim='f')[0] #행에서 앞자리 0 지우고, 가장 앞에 있는 숫자를 t라 하자 
            a.append(t)  # 리스트에 t값 추가
            if len(a) == 1: #막 추가된 값 하나 뿐이라면,
                pass #지나가
            elif a[-2] == a[-1]: #추가된 인형이 연속으로 같다면,
                del a[-1] 
                del a[-1]  #인형 두개 터뜨리고
                answer += 2 #답에 2 추가
            else: #막 시작한 것도 아니고, 인형이 연속으로 같지도 않으면
                pass #그냥 지나가
        except IndexError:  #np.trim_zero에서 빈행은 0으로 만들 수 없어 오류가 나면,
            pass            #그냥 지나가
        doll_pull(c) #인형뽑기
    return answer

In [36]:
# 상준(moves)

# index 0 is out of bounds for axis 0 with size 0

In [37]:
board = [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]

moves = [1,5,3,5,1,2,1,4] #a_trans 의 index 0,4,2,4,0,1,0,3 을 찾는다 

In [38]:
solution(board, moves) #켈켈켈켈켘ㄹ켈

4
3
1
1
3
2
4


4

### 9 약수의 합

In [39]:
# 23/01/11 pm 11:23 시작

In [40]:
# #for문에 i 이해하기

n = 10
for i in range(n):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [41]:
#1번 실패작

def solution(n):
    answer = 0
    for i in range(n):
        if n%i==0:
            answer += i
            print(answer)
    return answer



# n = 12
# solution(n)
# ZeroDivisionError: integer division or modulo by zero

In [42]:
#2번 실패작

def solution(n):
    answer = 0
    for i in range(n):
        if n%(i+1)==0:
            answer += i
            print(answer)
    return answer



# n = 12
# solution(n)
# 결과값 오류: answer에 i에 1 추가 안해줌

In [43]:
#완성작

def solution(n):
    answer = 0
    for i in range(n):
        if n%(i+1)==0:
            answer += (i+1)
            print(answer)
    return answer

# n = 12
# solution(n)

In [44]:
solution(20)

1
3
7
12
22
42


42

### 10 서울에서 김서방 찾기

In [45]:
seoul = ["Jane", "Kim"]
# return = "김서방은 1에 있다"
seoul.index('Kim')

1

In [46]:
def solution(seoul):
    김서방위치 = seoul.index('Kim')
    answer = '김서방은 {}에 있다'.format(김서방위치)
    return answer

In [47]:
solution(seoul)

'김서방은 1에 있다'

### 11 문자열 내 p와 y의 개수

>대문자와 소문자가 섞여있는 문자열 s가 주어집니다. s에 'p'의 개수와 'y'의 개수를 비교해 같으면 True, 다르면 False를 return 하는 solution를 완성하세요. 'p', 'y' 모두 하나도 없는 경우는 항상 True를 리턴합니다. 단, 개수를 비교할 때 대문자와 소문자는 구별하지 않습니다.

> 예를 들어 s가 "pPoooyY"면 true를 return하고 "Pyy"라면 false를 return합니다.

In [48]:
# s = "pPoooyY"
# answer = true

# s = "Pyy"
# answer = false

In [49]:
def solution(s):
    if (s.count('p') + s.count('P')) == (s.count('y') + s.count('Y')):
        answer = True
    else:
        answer = False
    return answer

In [50]:
s = "pPoooyY"
s.count('t') == s.count('c')


True

In [51]:
s = "pPoooyY"
s.count('c')

0

### 12 체육복

In [52]:
# s= [1,2,3]
# s.index(4)

# ValueError                                Traceback (most recent call last)

In [53]:
# def solution(n, lost, reserve):

    
        

    
    
#         체육복빌려주기(n, lost, reserve)
        
#     else:
#         def 체육복빌려주기(n, lost, reserve):
#             finally_lost = len(lost)
#             for i in range(len(lost)):
#                 try:
#                     if (reserve.index((lost[i])-1)): #잃어버린 친구 앞번호에 여유친구가 여유복이 있다면,
#                         reserve.remove(reserve.index((lost[i])-1)) #빌려준 여유복 없애고,
#                         finally_lost = finally_lost -1
#                 except ValueError:
#                     try:
#                         if (reserve.index((lost[i])+1)): #잃어버린 친구 뒷번호에 여유친구가 여유복이 있다면,
#                             reserve.remove(reserve.index((lost[i])+1)) #빌려준 여유복 없애고,
#                             finally_lost = finally_lost -1
#                     except ValueError:
#                         pass
#         print('finally_lost:{}'.format(finally_lost))        
#         return finally_lost

#     return n - finally_lost +1

In [54]:
#교집합 함수 만들기

def 교집합함수(n, lost, reserve):
    교집합 = list(set(lost).intersection(reserve))
    if 교집합 != []: #두 리스트의 교집합이 있다면,
        print('교집합:{}'.format(교집합))
        print('교집합의 개수 :{}개'.format(len(교집합)))
        for i in range(len(교집합)): #교집합의 수만큼 반복
            print('교집합 값 {} 제거'.format(교집합[i]))
            lost.remove(교집합[i])
            reserve.remove(교집합[i])
        print('lost:{}'.format(lost))
        print('reserve:{}'.format(reserve))


# n = 5
# lost = [1,2,3,4,5]
# reserve = [1,3,5]
# # 정답: 5

# print(lost)
# 교집합함수(n, lost, reserve)
# print(lost)


In [55]:
# #체육복 빌려주는 함수
# def 체육복빌려주기함수(n, lost, reserve):
#     finally_lost = len(lost)
#     print('finally_lost:{}'.format(finally_lost))
#     for i in range(len(lost)):
#         잃어버린친구번호 = lost[i]
#         잃어버린친구앞번호 = lost[i]-1
#         잃어버린친구뒷번호 = lost[i]+1
#         try:
#             print('잃어버린친구번호:{}'.format(잃어버린친구번호))
#             if 잃어버린친구앞번호 in reserve: #잃어버린 친구 앞번호에 여유친구가 여유복이 있다면,
#                 print('reserve:{}'.format(reserve))
#                 reserve.remove(잃어버린친구앞번호) #빌려준 여유복 없애고,
#                 print('reserve:{}'.format(reserve))
#                 finally_lost = finally_lost -1
#                 print('finally_lost:{}'.format(finally_lost))
#         except ValueError:
#             try:
#                 print('잃어버린친구번호:{}'.format(잃어버린친구번호))
#                 if 잃어버린친구뒷번호 in reserve: #잃어버린 친구 앞번호에 여유친구가 여유복이 있다면,
#                     reserve.remove(잃어버린친구뒷번호) #빌려준 여유복 없애고,
#                     finally_lost = finally_lost -1
#                     print('finally_lost?:{}'.format(finally_lost))
#             except ValueError:
#                 pass     
#     print('finally_lost!!:{}'.format(finally_lost))
#     return n-finally_lost

# n = 10
# lost = [2,4]
# reserve = [3,5]
# 체육복빌려주기함수(n, lost, reserve)

In [56]:
# n = 5
# lost = [4]
# reserve = [3]
# 체육복빌려주기함수(n, lost, reserve)

In [57]:
# #결합

# def solution(n,lost,reserve):
#     교집합함수(n, lost, reserve)
#     print(n,lost,reserve)
#     return 체육복빌려주기함수(n, lost, reserve)


# n = 10
# lost = [1,2,4]
# reserve = [1,3,5]
# solution(n,lost,reserve)


In [58]:
# b1 = [1,2,3,4,5,9,11,15]
# b2 = [3,4,6,7,8]
# b3 = list(set(b1).intersection(b2))
#교집합

In [59]:
# # n	lost	reserve	return
# # 5	[2, 4]	[1, 3, 5]	5
# # 5	[2, 4]	[3]	4
# # 3	[3]	[1]	2

# n = 5
# lost = [1,2,3,4,5]
# reserve = [1,3,5]
# # 정답: 5

# solution(n,lost,reserve)

In [60]:
# def 호호():
#     return 'gkgk'
# 호호()

In [61]:
# #오류발생
# a = [1]
# a.remove[1]
# # TypeError: 'builtin_function_or_method' object is not subscriptable

# #괄호가 대괄호가 아니라 소괄호다

In [62]:
# 리스트.remove(값)

체육복 2차 도전

In [63]:
# #교집합 함수 만들기

# def 교집합함수(n, lost, reserve):
#     교집합 = list(set(lost).intersection(reserve))
#     if 교집합 != []: #두 리스트의 교집합이 있다면,
#         print('교집합:{}'.format(교집합))
#         print('교집합의 개수 :{}개'.format(len(교집합)))
#         for i in range(len(교집합)): #교집합의 수만큼 반복
#             print('교집합 값 {} 제거'.format(교집합[i]))
#             lost.remove(교집합[i])
#             reserve.remove(교집합[i])
#         print('lost:{}'.format(lost))
#         print('reserve:{}'.format(reserve))
#     else:
#         print('교집함없음')


In [64]:
# # n	lost	reserve	return
# # 5	[2, 4]	[1, 3, 5]	5
# # 5	[2, 4]	[3]	4
# # 3	[3]	[1]	2

# n = 5
# lost = [1,2,3,4,5]
# reserve = [1,3,5]
# # 정답: 5

# solution(n,lost,reserve)

In [65]:

# n = 6
# lost = [1,2,4]
# reserve = [3,4,5]
# # 정답: 5

# # solution(n,lost,reserve)
# 교집합함수(n, lost, reserve)


In [66]:
def 여유치수줄이기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]-1
    print('치수줄인reserve:{}'.format(reserve)) #줄어든 여유분 체육복 치수

In [67]:
def 여유치수늘리기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]+2
    print('원상복귀 후 치수늘린 reserve:{}'.format(reserve)) #치수늘린 여유분 체육복 치수

In [68]:
n = 6
lost = [1,2,4]
reserve = [3,4,5]

def solution(n, lost, reserve):
    교집합함수(n, lost, reserve)
    여유치수줄이기(n,lost,reserve)
    교집합함수(n, lost, reserve)
    여유치수늘리기(n,lost,reserve)
    교집합함수(n, lost, reserve)
    return n-len(lost)

In [69]:
# solution(n, lost, reserve)

In [70]:
# 정의

def 교집합함수(n, lost, reserve):
    교집합 = list(set(lost).intersection(reserve))
    if 교집합 != []: #두 리스트의 교집합이 있다면,
        print('교집합:{}'.format(교집합))
        print('교집합의 개수 :{}개'.format(len(교집합)))
        for i in range(len(교집합)): #교집합의 수만큼 반복
            print('교집합 값 {} 제거'.format(교집합[i]))
            lost.remove(교집합[i])
            reserve.remove(교집합[i])
        print('lost:{}'.format(lost))
        print('reserve:{}'.format(reserve))
    else:
        print('교집함없음')


def 여유치수줄이기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]-1
    print('치수줄인reserve:{}'.format(reserve)) #줄어든 여유분 체육복 치수


def 여유치수늘리기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]+2
    print('원상복귀 후 치수늘린 reserve:{}'.format(reserve)) #치수늘린 여유분 체육복 치수


def solution(n, lost, reserve):
    교집합함수(n, lost, reserve)
    여유치수줄이기(n,lost,reserve)
    교집합함수(n, lost, reserve)
    여유치수늘리기(n,lost,reserve)
    교집합함수(n, lost, reserve)
    return n-len(lost)


In [71]:
# 정의

def 교집합함수(n, lost, reserve):
    교집합 = list(set(lost).intersection(reserve))
    if 교집합 != []:
        for i in range(len(교집합)):
            lost.remove(교집합[i])
            reserve.remove(교집합[i])



def 여유치수1줄이기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]-1




def 여유치수1늘리기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]+1



def 여유치수2줄이기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]-2




def 여유치수2늘리기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]+2


def 늘리기먼저(a,b, c):
    교집합함수(a, b, c)
    여유치수1늘리기(a,b,c)
    교집합함수(a, b, c)
    여유치수2줄이기(a,b,c)
    교집합함수(a, b, c)
    return a-len(b)

def 줄이기먼저(d, e, f):
    교집합함수(d, e, f)
    여유치수1줄이기(d,e,f)
    교집합함수(d, e, f)
    여유치수2늘리기(d,e,f)
    교집합함수(d, e, f)
    return d-len(e)


def solution(n, lost, reserve):
    lost.sort()
    reserve.sort()
    try:
        if(1 in reserve):
            return 늘리기먼저(n, lost, reserve)
    except ValueError:
        pass
    return 줄이기먼저(n, lost, reserve)

In [72]:
# #테스트 17,18,19,20, 25 틀림

# n = 10
# lost = [2,4  ,   7,9]
# reserve = [1,3  ,  8,10]

# solution(n, lost, reserve)

# #현재 상황에서 체육복을 줄여버리면 0,2가 되고, 2를 먼저 빌려줘버리면, 
# # 나중에 늘려도 2만남아서.. 4번에게 빌려줄 수가 없음.
# # 물론 치수 늘린거 먼저해도 같은 문제가 충분히 발생할듯

# # 여유치수늘리기(n, lost, reserve)

In [73]:
# n = 10
# lost = [2,4]
# reserve = [3,5]

# solution(n, lost, reserve)

3차

In [74]:
# n = 10
# lost = [2,4  , 6,  7,9]
# reserve = [1,3  ,  8,10]

# # solution(n, lost, reserve)

In [75]:
def 교집합함수(n, lost, reserve):
    교집합 = list(set(lost).intersection(reserve))
    if 교집합 != []:
        for i in range(len(교집합)):
            lost.remove(교집합[i])
            reserve.remove(교집합[i])

In [76]:
# 교집합함수(n,lost,reserve)
# print(n,lost,reserve)

# # lost[0] = 2
# ori = 0
# for i in range(len(lost)):
#     if (lost[i]-1) in reserve:
#         print('yes') 
#         reserve.remove(lost[i]-1)
#         print(reserve)
#         ori += 1
#     elif (lost[i]+1) in reserve:
#         print('sure')
#         reserve.remove(lost[i]+1)
#         ori += 1
#     else:
#         print('not here')

# print(n,lost,reserve)
# print(ori)

In [77]:
# def 교집합함수(n, lost, reserve):
#     교집합 = list(set(lost).intersection(reserve))
#     if 교집합 != []:
#         for i in range(len(교집합)):
#             lost.remove(교집합[i])
#             reserve.remove(교집합[i])

# def solution(n,lost,reserve):
#     교집합함수(n,lost,reserve)
#     Salvation = 0
#     for i in range(len(lost)):
#         if (lost[i]-1) in reserve:
#             reserve.remove(lost[i]-1)
#             Salvation += 1
#         elif (lost[i]+1) in reserve:
#             reserve.remove(lost[i]+1)
#             Salvation += 1
#         else:
#             pass
#     return n-len(lost)+Salvation

In [78]:
#해결!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

def 교집합함수(n, lost, reserve):
    교집합 = list(set(lost).intersection(reserve))
    if 교집합 != []:
        for i in range(len(교집합)):
            lost.remove(교집합[i])
            reserve.remove(교집합[i])

def solution(n,lost,reserve):
    lost.sort()
    reserve.sort()
    교집합함수(n,lost,reserve)
    Salvation = 0
    for i in range(len(lost)):
        if (lost[i]-1) in reserve:
            reserve.remove(lost[i]-1)
            Salvation += 1
        elif (lost[i]+1) in reserve:
            reserve.remove(lost[i]+1)
            Salvation += 1
        else:
            pass
    return n-len(lost)+Salvation

In [79]:
n = 10
lost = [2,4  ,  7,9]
reserve = [1,3  ,  8,10]

solution(n,lost,reserve)

10

### 13 두 정수 사이의 합

In [80]:
# 두 정수 a, b가 주어졌을 때 a와 b 사이에 속한 모든 정수의 합을 리턴하는 함수, solution을 완성하세요.
# 예를 들어 a = 3, b = 5인 경우, 3 + 4 + 5 = 12이므로 12를 리턴합니다.

In [81]:
#내 코드
def solution(a, b):
    if a<b:
        answer = (a+b)*(b-a+1)/2
    elif a>b:
        answer = (a+b)*(a-b+1)/2
    else:
        answer = a
    return answer

In [82]:
#다른사람 코드
def adder(a, b):
    if a > b: a, b = b, a
    return sum(range(a,b+1))

14 문자열 다루기 기본

In [83]:
# 문자열 s의 길이가 4 혹은 6이고, 숫자로만 구성돼있는지 확인해주는 함수, solution을 완성하세요. 예를 들어 s가 "a234"이면 False를 리턴하고 "1234"라면 True를 리턴하면 됩니다.

In [84]:
# def solution(s):
#     if (len(s)==4 or len(s)==6):
#         try:
#             if int(s) ==0:
#                 answer = True
#             else: 
#                 anwer = False
#         except:
#             anwer = False
#     try:
#         if int(s):
#             if (len(s)==4 or len(s)==6):
#                 answer = True
#             else:
#                 answer = False
#         else:
#             answer = False
#     except:
#         answer = False
#     return answer

In [85]:
#문자열의 길이가 4 or 6인가요?
#문자가 숫자로만 되어있나요?
#그러면 합격!!!!


def solution(s):
    if len(s)==4 or len(s)==6:
        try:
            if type(int(s)) == int:
                answer = True
        except:
            answer = False
    else:
        answer = False
    return answer

In [86]:
s='0000'
solution(s)

True

In [87]:
#다른사람의 코드

def alpha_string46(s):
    try:
        int(s)
    except:
        return False
    return len(s) == 4 or len(s) == 6 

### 16 나누어 떨어지는 숫자 배열

In [88]:
# array의 각 element 중 divisor로 나누어 떨어지는 값을 오름차순으로 정렬한 배열을 반환하는 함수, solution을 작성해주세요.
# divisor로 나누어 떨어지는 element가 하나도 없다면 배열에 -1을 담아 반환하세요.

In [89]:
arr = [5, 9, 7, 10]
divisor = 5
# return = [5, 10]

In [90]:
# 내 스타일!
def solution(arr, divisor):
    answer = []
    for i in range(len(arr)):
        if arr[i]%divisor == 0:
            answer.append(arr[i])
    if answer == []:
        answer = [-1]
    answer.sort()
    return answer

In [91]:
solution(arr, divisor)

[5, 10]

In [92]:
# # 예원님 스타일!

# def solution(arr, divisor):
#     for i in range(len(arr)):
#         # print(i)
#         if arr[i]%divisor != 0:
#             print(arr[i])
#             arr.remove(arr[i])
#         else :
#             pass
#     return arr

In [93]:
# # 변경

# def solution(arr, divisor):
#     for i in range(-1,-len(arr)-1,-1):
#         print(arr[i])
#         if arr[i]%divisor != 0:
#             print(arr)
#             pass
#         else:
#             print(arr)
#             arr.pop(10)
#             print(arr)
#     return arr

#     #실패

In [94]:
a = [1,2,3,4,5]
for i in range(-1,-len(a)-1,-1):
    print(a[i])

# -1부터 a길이까지, 역순으로 a값 뽑기

5
4
3
2
1


In [95]:
arr = [5, 9, 7, 10]
divisor = 5
# return = [5, 10]

In [96]:
solution(arr, divisor)

[5, 10]

#### 짝수 홀수 개수

In [36]:
def solution(num_list):
    answer = [0,0]
    if 0 in num_list:
        answer = [1,0]
        num_list.remove(0)
    for i in num_list:
        if i%2 == 0:
            answer[0] += 1
        else:
            answer[1] += 1
    return answer

In [37]:
num_list = [ 0, 1, 2, 3, 4, 5, 7,15]
solution(num_list)

[3, 5]

#### 아이스 아메리카노

In [46]:
def solution(money):
    answer = []
    아메리카노 = 5500
    answer.append(money//아메리카노)
    answer.append(money%아메리카노)
    return answer

In [47]:
money = 0
solution(money)

[0, 0]

#### 삼각형의 완성조건 (1)

In [55]:
def solution(sides):
    sides.sort()
    print(sides)
    if sides[0]+sides[1] > sides[2]:
        answer = 1
    else:
        answer = 2
    return answer

In [56]:
sides = [3, 6, 2] #[1,2,3]
solution(sides)

[2, 3, 6]


2

In [57]:
#다른사람 코드
def solution(sides):
    sides.sort()
    return 1 if sides[0]+sides[1]>sides[2] else 2

In [58]:
#다른사람코드2

def solution(sides):
    return 1 if max(sides) < (sum(sides) - max(sides)) else 2

# 3주차

### 17 예산

In [97]:
# S사에서는 각 부서에 필요한 물품을 지원해 주기 위해 부서별로 물품을 구매하는데 필요한 금액을 조사했습니다. 그러나, 전체 예산이 정해져 있기 때문에 모든 부서의 물품을 구매해 줄 수는 없습니다. 그래서 최대한 많은 부서의 물품을 구매해 줄 수 있도록 하려고 합니다.

# 물품을 구매해 줄 때는 각 부서가 신청한 금액만큼을 모두 지원해 줘야 합니다. 예를 들어 1,000원을 신청한 부서에는 정확히 1,000원을 지원해야 하며, 1,000원보다 적은 금액을 지원해 줄 수는 없습니다.

# 부서별로 신청한 금액이 들어있는 배열 d와 예산 budget이 매개변수로 주어질 때, 최대 몇 개의 부서에 물품을 지원할 수 있는지 return 하도록 solution 함수를 완성해주세요.

#오후 7시 20분

In [98]:
d = [1,3,2,5,4]
budget = 9
# return 3

In [99]:
#내 풀이:20분 소요
def solution(d,budget):
    d.sort()
    print(d)
    d_sum = 0
    answer = 0
    for i in range(len(d)):
        d_sum += d[i]
        if d_sum <= budget:
            print(d_sum)
            answer += 1
        else:
            return answer
    return answer

In [100]:
d = [2,2,3,3]
budget = 10

solution(d,budget)

# 7시 50분!! 

[2, 2, 3, 3]
2
4
7
10


4

In [101]:
# 다른 사람 코드

def solution(d, budget):
    d.sort()
    while budget < sum(d):
        d.pop()
    return len(d)

In [102]:
# 다른 사람 코드

def solution(d, budget):
    d.sort()
    cnt = 0
    # if sum(d) == budget :
    #     answer = len(d)
    # elif sum(d) < budget :
    #     for i in d :
    #         budget -= i
    #         cnt += 1
    #         answer = cnt
    # else :
    for i in d :
        budget -= i
        if budget < 0 :
               break
        cnt += 1
    answer = cnt
    return answer

### 18 2016년

In [103]:
# 2016년 1월 1일은 금요일입니다. 2016년 a월 b일은 무슨 요일일까요? 두 수 a ,b를 입력받아 2016년 a월 b일이 무슨 요일인지 리턴하는 함수, solution을 완성하세요. 요일의 이름은 일요일부터 토요일까지 각각 SUN,MON,TUE,WED,THU,FRI,SAT

# 입니다. 예를 들어 a=5, b=24라면 5월 24일은 화요일이므로 문자열 "TUE"를 반환하세요.

In [104]:
a = 5
b = 24
# result = "TUE"

In [105]:
import datetime

In [106]:
days = ["MON","TUE","WED","THU","FRI","SAT","SUN"]

def solution(a,b):
    return days[datetime.date(2016,a,b).weekday()]

In [107]:
solution(1,1)

# weekday 에서 괄호를 빼먹어서 에러발생
# TypeError: list indices must be integers or slices, not builtin_function_or_method

'FRI'

In [108]:
# 금요일이 아닌 목요일로 출력되는 결과가 있었는데.. 이유는
# datetime 순서는 월요일부터 매핑되기 때문이다.
# 맨 처음 sun으로 시작되어 매핑이 안맞았다.

### 19 자릿수 더하기

In [109]:
# 자연수 N이 주어지면, N의 각 자릿수의 합을 구해서 return 하는 solution 함수를 만들어 주세요.
# 예를들어 N = 123이면 1 + 2 + 3 = 6을 return 하면 됩니다.

In [110]:
# 오 나 이거 좀 잘푼듯
def solution(n):
    answer = 0
    for i in str(n):
        answer += int(i)
    return answer

In [111]:
N = 123
solution(N)

6

### 20 최대공약수와 최소공배수

In [112]:
# 두 수를 입력받아 두 수의 최대공약수와 최소공배수를 반환하는 함수, solution을 완성해 보세요. 배열의 맨 앞에 최대공약수, 그다음 최소공배수를 넣어 반환하면 됩니다. 예를 들어 두 수 3, 12의 최대공약수는 3, 최소공배수는 12이므로 solution(3, 12)는 [3, 12]를 반환해야 합니다.

In [113]:
import math



def solution(n, m):
    answer = []
    answer.append(math.gcd(n,m))
    answer.append(math.lcm(n,m))
    return answer

In [114]:
n = 2
m = 5

solution(n,m)

[1, 10]

In [115]:
# AttributeError: module 'math' has no attribute 'lcm'

# def lcm(a,b):
#   return (a * b) // math.gcd(a,b)
# 파이썬 3.9버전부터 가능ㅡ 그래서 그 전 버전은 없애야함.

In [116]:
import math

def lcm(a,b):
    return (a * b) // math.gcd(a,b)

def solution(n, m):
    answer = []
    answer.append(math.gcd(n,m))
    answer.append(lcm(n,m))
    return answer

### 21 하샤드 수

In [117]:
# 자리수 더하기
def 자리수더하기(n):
    자리수합 = 0
    for i in str(n):
        자리수합 += int(i)
    return 자리수합

def solution(x):
    if x%자리수더하기(x) == 0:
        return True
    else:
        return False   

In [118]:
solution(13)

False

### 22 문자열 내 마음대로 정렬하기

#### 1차시도 실패

In [2]:
def solution(strings,n):
    new_index = []
    for i in range(len(strings)):
        new_index.append(strings[i][n])
        print(new_index)

In [3]:
# strings = ["sun", "bed", "car"]
# n = 1
# solution(strings,n)

# # 값을 줘서 순서를 매겨? ㅋㅋㅋ
# # [3,2,1 순서임]

['u']
['u', 'e']
['u', 'e', 'a']


In [33]:
# strings.sort()
# solution(strings,n)

['e']
['e', 'a']
['e', 'a', 'u']


TypeError: 'NoneType' object is not callable

In [31]:
# from string import ascii_lowercase

# alphabet_dict = {}
# for i in ascii_lowercase:
#     alphabet_dict[i] = ascii_lowercase.index(i)+1

# print(alphabet_dict)


{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26}


In [44]:
# from string import ascii_lowercase

# def solution(strings,n):
#     alphabet_dict = {}
#     for i in ascii_lowercase:
#         alphabet_dict[i] = ascii_lowercase.index(i)+1
#     reverse_index = {v:k for k,v in alphabet_dict.items()}

#     strings.sort()

#     new_index = []
#     for i in range(len(strings)):
#         new_index.append(strings[i][n])

#     new_int_index = []
#     for i in range(len(strings)):
#         new_int_index.append(alphabet_dict[new_index[i]])
#     new_int_index.sort()

#     answer_index = []
#     for i in range(len(strings)):
#         answer_index.append(reverse_index.get(new_int_index[i]))
#     print(answer_index)
#     return new_int_index

# # 너무 못생겼다....... 이건 아닌듯.......

#### 2차시도

In [46]:
strings = ["sun", "bed", "car"]
n = 1

In [82]:
def solution(strings,n):
    new_index = []
    for i in range(len(strings)):
        new_index.append(strings[i][n] + strings[i])
    new_index.sort()
    # print(new_index) ['acar', 'ebed', 'usun']

    cut_new_index = [] 
    for i in range(len(strings)):
        cut_new_index.append(new_index[i][1:])
    return cut_new_index

In [83]:
solution(strings,n)

['acar', 'ebed', 'usun']


['car', 'bed', 'sun']

In [ ]:
# # 다른 이의 코드

def strange_sort(strings, n):
    '''strings의 문자열들을 n번째 글자를 기준으로 정렬해서 return하세요'''
    return sorted(strings, key=lambda x: x[n])

    #람다에 대해 알아봐야할듯...

### 23 모의고사

In [1]:
# 1번 수포자가 찍는 방식: 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, ... (5개 반복)
# 2번 수포자가 찍는 방식: 2, 1, 2, 3, 2, 4, 2, 5, 2, 1, 2, 3, 2, 4, 2, 5, ...(8개 반복)
# 3번 수포자가 찍는 방식: 3, 3, 1, 1, 2, 2, 4, 4, 5, 5, 3, 3, 1, 1, 2, 2, 4, 4, 5, 5, ...(10개 반복)

In [ ]:
answers = [1,2,3,4,5] # [1]
answers = [1,3,2,4,2] # [1,2,3]

In [7]:
import math

def lcm(a,b,c):
    return (a * b * c) // math.gcd(a,b,c)

lcm(5,8,10)

400

In [6]:
#처음에는 answer 배열, 1,2,3번의 최소공배수를 따져서 반복되는만큼 중, 얼마나 많이 맞추는지로 계산하려고했는데..answer가 1만개까지 된다고 한다.. answer가 커질수록 의미가 없어질듯.. ㅠ

In [8]:
#무식한? 방법으로는 
# 1) answer개수확인
# 2) 수포자배열을 answer 개수만큼씩 늘리거나 줄이기
# 3) 같은게 몇개인지 체크
# 4) 가장 많은것으로 return

In [51]:
answers = [1,2,3,4,5,4,2,1,5,4,2,1,3,3,5,1,2,4]
# answers = [1,2,3,4,5]
# 수포자1 = [1,2,3,4,5]
# 수포자2 = [2, 1, 2, 3, 2, 4, 2, 5]



def 수포자의배열(수포자이름):
    if len(answers)>len(수포자이름):
        수포자_배열_늘리기 = len(answers)//len(수포자이름) + 1
        새로운_수포자_배열 = 수포자이름*수포자_배열_늘리기
    else:
        새로운_수포자_배열 = 수포자이름

    찍어맞춘_수포자_배열 = 0
    for i in range(len(answers)):
        if answers[i] == 새로운_수포자_배열[0:len(answers)][i]:
            찍어맞춘_수포자_배열 +=1
        else:
            pass
    return 찍어맞춘_수포자_배열



# 수포자2 = [2, 1, 2, 3, 2, 4, 2, 5]
# print(수포자2[0:len(answers)])
# 수포자3 = [3, 3, 1, 1, 2, 2, 4, 4, 5, 5]
# print(수포자3[0:len(answers)])

In [52]:
def 가장높은점수체크함수(answers):
    수포자1 = [1, 2, 3, 4, 5]
    수포자2 = [2, 1, 2, 3, 2, 4, 2, 5]
    수포자3 = [3, 3, 1, 1, 2, 2, 4, 4, 5, 5]

    a = 수포자의배열(수포자1)
    b = 수포자의배열(수포자2)
    c = 수포자의배열(수포자3)
    
    if a>b and a>c:
        return [1]
    elif a==b and a>c:
        return [1,2]
    elif a>b and a==c:
        return [1,3]
    elif a==b==c:
        return [1,2,3]
    elif a==b and a<c:
        return [3]
    elif a<b and a==c:
        return [2]
    elif a<b and b==c:
        return [2,3]
    elif a<c and b<c:
        return [3]
    elif a<b and c<b:
        return [2]


In [53]:
# answers = [1,2,3,4,5]
# answers = [1,3,2,4,2]

가장높은점수체크함수(answers)

[1]

In [54]:
# 상준 제출용

def solution(answers):
    수포자1 = [1, 2, 3, 4, 5]
    수포자2 = [2, 1, 2, 3, 2, 4, 2, 5]
    수포자3 = [3, 3, 1, 1, 2, 2, 4, 4, 5, 5]

    def 수포자의배열(수포자이름):
        if len(answers)>len(수포자이름):
            수포자_배열_늘리기 = len(answers)//len(수포자이름) + 1
            새로운_수포자_배열 = 수포자이름*수포자_배열_늘리기
        else:
            새로운_수포자_배열 = 수포자이름

        찍어맞춘_수포자_배열 = 0
        for i in range(len(answers)):
            if answers[i] == 새로운_수포자_배열[0:len(answers)][i]:
                찍어맞춘_수포자_배열 +=1
            else:
                pass
        return 찍어맞춘_수포자_배열
    
    a = 수포자의배열(수포자1)
    b = 수포자의배열(수포자2)
    c = 수포자의배열(수포자3)
    
    if a>b and a>c:
        return [1]
    elif a==b and a>c:
        return [1,2]
    elif a>b and a==c:
        return [1,3]
    elif a==b==c:
        return [1,2,3]
    elif a==b and a<c:
        return [3]
    elif a<b and a==c:
        return [2]
    elif a<b and b==c:
        return [2,3]
    elif a<c and b<c:
        return [3]
    elif a<b and c<b:
        return [2]

In [56]:
solution(answers)


10


In [ ]:
#다른사람 반복에는 싸이클!
from itertools import cycle

def solution(answers):
    giveups = [
        cycle([1,2,3,4,5]),
        cycle([2,1,2,3,2,4,2,5]),
        cycle([3,3,1,1,2,2,4,4,5,5]),
    ]
    scores = [0, 0, 0]
    for num in answers:
        for i in range(3):
            if next(giveups[i]) == num:
                scores[i] += 1
    highest = max(scores)

    return [i + 1 for i, v in enumerate(scores) if v == highest]

### 24 두 개 뽑아서 더하기

In [16]:
from itertools import combinations


def solution(numbers):
    answer = []
    for i in range(len(list(combinations(numbers, 2)))):
        answer.append(list(combinations(numbers, 2))[i][0]+list(combinations(numbers, 2))[i][1])
    answer = list(set(answer))
    answer.sort() #오류나서 위치 변경
    return answer

# numbers = [2,1,3,4,1,0,0,0,3,3,5,36,100,6,44,66,66]
numbers = [2,1,3,4,1,0]

solution(numbers)

[1, 2, 3, 4, 5, 6, 7]

### 25 시저 암호

In [53]:
# from string import ascii_lowercase


# sl = ascii_lowercase*2
# ll = ascii_lowercase.upper()*2

# s = "A  B"
# print(len(s))
# s[3].isspace() 

# print(sl)



In [ ]:
# from string import ascii_lowercase



# def solution(s,n):
#     sl = ascii_lowercase*2
#     ll = ascii_lowercase.upper()*2
#     answer = []
#     for i in range(len(s)):
#         print(s[i])
#         if s[i].isspace(): #빈칸일때
#             answer.append(" ")
#         else: #빈칸 아닐때
#             if s[i].isupper(): #대문자면
#                 index_s = ll.find(s[i]) #인덱스번호
#                 new_index_s = index_s + n #몇칸옮길지 결정
#                 answer.append(ll[new_index_s])
#             else: #소문자면
#                 index_s = sl.find(s[i]) #인덱스번호
#                 new_index_s = index_s + n #몇칸옮길지 결정
#                 answer.append(sl[new_index_s])
#     answer = ''.join(answer)
#     return answer


# solution(s,n)


In [70]:
'a'<'b'
#문자도 부등호가 가능하다 ㄷㄷㄷ

True

In [ ]:
# # 다른 사람 풀이
# def solution(s, n):
#     answer = ''
#     for i in s:
#         if i:
#             if i >= 'A' and i <= 'Z':
#                 answer += chr((ord(i) - ord('A') + n) % 26 + ord('A'))
#             elif i >= 'a' and i <= 'z':
#                 answer += chr((ord(i) - ord('a') + n) % 26 + ord('a'))
#             else : answer += ' '
#     return answer

### 26 이상한 문자 만들기

In [25]:
s = "try hello world"
my_list = s.split(' ')

print(my_list)


['try', 'hello', 'world']


In [19]:
answer = []
for k in range(len(my_list)):
    small_answer = []
    for s in range(len(my_list[k])):
        if s%2 == 0:
            small_answer.append(my_list[k][s].upper())
        else:
            small_answer.append(my_list[k][s].lower())
    answer.append("".join(small_answer))
print(answer)

['TrY', 'HeLlOk', 'WoRlD']


In [35]:
def solution(s):
    my_list = s.split(' ')
    answer = []
    for k in range(len(my_list)):
        small_answer = []
        for s in range(len(my_list[k])):
            if s%2 == 0:
                small_answer.append(my_list[k][s].upper())
            else:
                small_answer.append(my_list[k][s].lower())
        answer.append("".join(small_answer))
    return " ".join(answer)

In [36]:
s = "try hellok world"
solution(s)

'TrY HeLlOk WoRlD'

# 4주차

### 27 나머지가 1이 되는 수 찾기

In [22]:
n = 10
result = 3

In [ ]:
# 자연수 n이 매개변수로 주어집니다. n을 x로 나눈 나머지가 1이 되도록 하는 가장 작은 자연수 x를 return 하도록 solution 함수를 완성해주세요. 답이 항상 존재함은 증명될 수 있습니다.

In [23]:
# n값에서 1을 빼고, 그 값의 약수 중 가장 작은 값을 구하자.

In [33]:
def solution(n):
    k = n-1 #나머지가 1이니까, 1을 빼줘서 딱 떨어지는 값 만들기
    for i in range(2,k+1): #2부터 k+1 까지 돌리자
        if k%i == 0: #나누어 떨어지면 끝!
            return i


### 28 약수 구하기

In [34]:
# 정수 n이 매개변수로 주어질 때, n의 약수를 오름차순으로 담은 배열을 return하도록 solution 함수를 완성해주세요.

In [35]:
n = 24
result = [1, 2, 3, 4, 6, 8, 12, 24]

In [36]:
def solution(n):
    answer = []
    for i in range(1,n+1): #2부터 k+1 까지 돌리자
        if n%i == 0: #나누어 떨어지면 끝!
            answer.append(i)
    return answer

### 29 배열 회전시키기

In [38]:
# 정수가 담긴 배열 numbers와 문자열 direction가 매개변수로 주어집니다. 배열 numbers의 원소를 direction방향으로 한 칸씩 회전시킨 배열을 return하도록 solution 함수를 완성해주세요.

In [82]:
direction = 'right'
result = [3,1,2]

In [ ]:
# from collections import deque


# numbers = [1,2,3]

# def solution(numbers):
#     deq = deque(numbers)
#     deq.rotate(1)
#     print(deq)
#     print(deq.rotate(1))
#     print(list(deq.rotate(1)))

#     # if direction == "right":
#     #     return list(deq.rotate(1))
#     # else:
#     #     return list(deq.rotate(-1))

# solution(numbers)

In [90]:
from collections import deque

def solution(numbers, direction):
    deq = deque(numbers)
    if direction == "right":
        deq.rotate(1)
        new_numbers = list(deq)
        return new_numbers
    else:
        deq.rotate(-1)
        new_numbers = list(deq)
        return new_numbers

[3, 1, 2]

In [ ]:
# deq.rotate(1) 값은 출력되지 않는다. 돌리는 함수고 결과물을 보여주지 않는다.
# 결과물은 deq를 찍어봐야한다.

In [68]:
# list_x = [1,2,3]
# t = deque(list_x)
# t.rotate(1)
# print(t)

deque([3, 1, 2])


### 30 최댓값 만들기 (2)

In [1]:
# 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소 중 두 개를 곱해 만들 수 있는 최댓값을 return하도록 solution 함수를 완성해주세요.

In [30]:
numbers = [-1, -2,3,4,5,6]
result = 15

In [32]:
# #가장 짝수중 가장 큰 수 두개 찾고
# # 홀수중 가장 큰 수 두개 찾고
# # 곱한 값 중에 큰 값을 리턴


# def solution(numbers):
#     # if len(numbers)<4:

#     가장큰수 = max(numbers)
#     numbers.remove(가장큰수)
#     print(numbers)
#     두번째큰수 = max(numbers)
#     큰수들의곱 = 가장큰수*두번째큰수
#     print(큰수들의곱)

#     가장작은수 = min(numbers)
#     print(numbers)
#     numbers.remove(min(numbers))
#     print(numbers)
#     두번째작은수 = min(numbers)
#     작은수들의곱 = 가장작은수*두번째작은수
#     print(작은수들의곱)


#     if 큰수들의곱 < 작은수들의곱:
#         return 작은수들의곱
#     else:
#         return 큰수들의곱

# solution(numbers)

# #이거는 문제가.. 넘버스가 4개 미만이면 오류발생함.. 
# #빼는건 함부로 하면 안되는듯..

In [ ]:
#순서 재배열 위에서 앞에서 두개, 뒤에서 두개 빼서 비교

def solution(numbers):
    numbers.sort()
    if numbers[-1]*numbers[-2] > numbers[0]*numbers[1]:
        return numbers[-1]*numbers[-2]
    else:
        return numbers[0]*numbers[1]

In [ ]:
# #다른사람 풀이... 좋다..
# def solution(numbers):
#     numbers.sort()
#     return max(numbers[0] * numbers[1], numbers[-1] * numbers[-2])

### 31 피자 나눠 먹기 (2)

In [ ]:
# 머쓱이네 피자가게는 피자를 여섯 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 매개변수로 주어질 때, n명이 주문한 피자를 남기지 않고 모두 같은 수의 피자 조각을 먹어야 한다면 최소 몇 판을 시켜야 하는지를 return 하도록 solution 함수를 완성해보세요.

In [33]:
n =10

In [49]:
import math

def solution(n):
    gcd = math.gcd(n, 6)
    lcm = (gcd)*(n/gcd)*(6/gcd)
    return int(lcm/6)

### 32 외계행성의 나이

In [50]:
# 우주여행을 하던 머쓱이는 엔진 고장으로 PROGRAMMERS-962 행성에 불시착하게 됐습니다. 입국심사에서 나이를 말해야 하는데, PROGRAMMERS-962 행성에서는 나이를 알파벳으로 말하고 있습니다. a는 0, b는 1, c는 2, ..., j는 9입니다. 예를 들어 23살은 cd, 51살은 fb로 표현합니다. 나이 age가 매개변수로 주어질 때 PROGRAMMER-962식 나이를 return하도록 solution 함수를 완성해주세요.

In [74]:
# age = 23

def solution(age):
    a = 'abcdefghij'
    answer = []
    for i in range(len(str(age))):
        answer.append(a[int(str(age)[i])])
    return ''.join(answer)

# solution(age)
#더럽게 풀었네.. ㅋㅋ; ㅠ

'cd'

In [71]:
# age = [1,2,3]
# age[str(2)]
# 문자2로는 인덱스를 매길 수 없다..

TypeError: list indices must be integers or slices, not str

### 33 369게임

In [75]:
# 머쓱이는 친구들과 369게임을 하고 있습니다. 369게임은 1부터 숫자를 하나씩 대며 3, 6, 9가 들어가는 숫자는 숫자 대신 3, 6, 9의 개수만큼 박수를 치는 게임입니다. 머쓱이가 말해야하는 숫자 order가 매개변수로 주어질 때, 머쓱이가 쳐야할 박수 횟수를 return 하도록 solution 함수를 완성해보세요.

In [95]:
order = 29423

def solution(order):
    count = 0
    for i in range(len(str(order))):
        if str(order)[i] == str(3):
            count += 1
        elif str(order)[i] == str(6):
            count += 1
        elif str(order)[i] == str(9):
            count += 1
        else: 
            pass
    return count

solution(order)

2

In [87]:
str(2) == str(2)

True

In [ ]:
# # 이거다 내가 만들고 싶었던 것... ㅋㅋ ㅠ 다른사람코드.

# def solution(order):
#     answer = 0
#     order = str(order)
#     return order.count('3') + order.count('6') + order.count('9')

### 34 인덱스 바꾸기

In [1]:
# 문자열 my_string과 정수 num1, num2가 매개변수로 주어질 때, my_string에서 인덱스 num1과 인덱스 num2에 해당하는 문자를 바꾼 문자열을 return 하도록 solution 함수를 완성해보세요.

In [2]:
my_string = 'hello'
num1 = 1
num2 = 2

result = 'hlelo'

In [12]:
# my_string.replace(my_string[num1], my_string[num2])
# my_string.replace(my_string[num2], my_string[num1])

# # 실패..

'heeeo'

In [35]:
new_string = list(my_string)
new_string[num1] = list(my_string)[num2]
new_string[num2] = list(my_string)[num1]
"".join(new_string)


'hlelo'

### 35 숫자찾기

In [36]:
# 정수 num과 k가 매개변수로 주어질 때, num을 이루는 숫자 중에 k가 있으면 num의 그 숫자가 있는 자리 수를 return하고 없으면 -1을 return 하도록 solution 함수를 완성해보세요.

In [48]:
num = 29183
k = 1

def solution(num,k):
    if str(k) in list(str(num)):
        return list(str(num)).index(str(k))+1
    else:
        return -1

solution(num,k)

2


3

### 36 콜라츠 추측

In [56]:
n = 1

def solution(n):
    answer = 0
    while n != 1:
        if n%2 == 0:
            n = n/2
            answer += 1
            if answer > 500:
                return -1
        else:
            n = n*3 +1
            answer += 1
            if answer > 500:
                return -1
    return answer

solution(n)



0

### 37 문자열 정렬하기 (2)

In [18]:
my_string = "Bcad"

def solution(my_string):
    a = list(my_string.lower())
    a.sort()
    return ''.join(a)


### 38 제일 작은 수 제거하기

In [31]:
arr = [4,3,2,1]

def solution(arr):
    if len(arr) <= 1:
        arr = [-1]
    else:
        arr.remove(min(arr))
    return arr

### 39 중복된 문자 제거


In [1]:
my_string = "people"

set(list(my_string))

# 셋으로 도전하였으나 순서가 망가져서 실패.
# 셋은 순서가 없다. 고로 만들 수 없다.
# 1차 실패

{'e', 'l', 'o', 'p'}

In [14]:
# 내 코드

def solution(my_string):
    answer = []
    for i in list(my_string):
        if i in answer: 
            pass 
        else: 
            answer.append(i)
    return "".join(answer)
    

In [ ]:
# not in 가능
# if i not in answer: 요런식


# 다른사람 코드

def solution(my_string):
    answer = ''
    for i in my_string:
        if i not in answer: #멋지다
            answer+=i
    return answer

### 40 합성수 찾기

In [34]:
n = 15

answer = 0
for i in range(1,n+1):
    a = 0
    for j in range(2, i):
        if i%j == 0:
            a+= 1
            break
    if a != 0:
        answer += 1
print(answer)

8


# 23년 2월 둘째주

### 41 기사단원의 무기

In [25]:
def y(n):

    a = []
    for i in range(1, int(n**(1/2)) + 1):
        if (n % i == 0):
            a.append(i) 
            if ( (i**2) != n) : 
                a.append(n // i)
    return len(a)

    
def solution(n,l,p):
    a=0
    for i in range(1,n+1):
        if y(i)>l:
            a+=p
        else:
            a+=y(i)
    return a

In [20]:
def getMyDivisor(n):

    divisorsList = []

    for i in range(1, int(n**(1/2)) + 1):
        if (n % i == 0):
            divisorsList.append(i) 
            if ( (i**2) != n) : 
                divisorsList.append(n // i)
    
    return len(divisorsList)

In [24]:
getMyDivisor(4)

3

### 42 음양 더하기

In [49]:
import numpy as np

def solution(absolutes, signs):
    for i in range(len(signs)):
        if signs[i] == True:
            signs[i] = 1
        else:
            signs[i] = -1
        
    absolutes = np.array(absolutes)
    signs = np.array(signs)
    answer = np.sum(absolutes*signs)

    return answer.tolist()



In [48]:
absolutes = [4,7,12]
signs = [True,False,True]


solution(absolutes, signs)

9

### 43 없는 숫자 더하기

In [51]:
import numpy as np

numbers = [1,2,3,4,6,7,8,0]

def solution(numbers):
    a = 1+2+3+4+5+6+7+8+9
    np_numbers = np.array(numbers)
    np_answer = a - np.sum(np_numbers)
    answer = np_answer.tolist()
    return answer


In [ ]:
def solution(numbers):
    a = 1+2+3+4+5+6+7+8+9
    answer = a - sum(numbers)
    return answer

### 44 모스부호 (1)

In [63]:
letter = ".... . .-.. .-.. ---"

def solution(letter):
    morse = { 
    '.-':'a','-...':'b','-.-.':'c','-..':'d','.':'e','..-.':'f',
    '--.':'g','....':'h','..':'i','.---':'j','-.-':'k','.-..':'l',
    '--':'m','-.':'n','---':'o','.--.':'p','--.-':'q','.-.':'r',
    '...':'s','-':'t','..-':'u','...-':'v','.--':'w','-..-':'x',
    '-.--':'y','--..':'z'
    }


    split_letter = letter.split(' ')
    a = []
    for i in split_letter:
        a.append(morse[i])
    return''.join(a)


hello


### 45 진료 순서 정하기

In [50]:
emergency = [30, 10, 23, 6, 100]	
# result = [3,1,2]

def solution(emergency):
    result = []
    sorted_emergency = sorted(emergency,reverse=True)
    for i in emergency:
        answer = sorted_emergency.index(i)+1
        result.append(answer)
    return result

solution(emergency)

[2, 4, 3, 5, 1]