2 행렬의 덧셈

In [257]:
import numpy as np

def solution(arr1,arr2):
    return (np.array(arr1) + np.array(arr2)).tolist()



In [258]:
arr1 = [[1,2],[2,3]]
type(arr1)

list

In [259]:
# 첫 실수
# 함수 정의할 때 : 안씀.


# 두번째 실수
# np.array(리스트) 기억이 안남.. (np변환만 10번 넘게 검색한듯.. 이제는 기억할 때가 되지 않았는가)


# 세번째 실수
# 타입오류남. 오류코드는.....
# TypeError: Object of type ndarray is not JSON serializable
# 그대로 검색해보니 어레이.tolist() 붙이면 리스트로 변환 됨.

3 수박수박수박수박수박수?

In [260]:
def solution(n):
    몫 = n//2
    나머지 = n%2
    answer = ('수박')*몫 + ('수')*나머지
    return answer

In [261]:
solution(2000)

'수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수

4 완주하지 못한 선수

In [262]:
def solution(participant, completion):
    participant.sort()
    completion.sort()
    for i in range(len(completion)):
        if participant[i] == completion[i]:
            continue
        else:
            return participant[i]
    return participant[-1]

7 핸드폰 번호 가리기

In [263]:
#나의 코드

def solution(phone_number):
    return phone_number.replace(phone_number[:-4],'*'*(len(phone_number)-4))
    # 핸드폰번호를 대채하는데, 다른부분은 놔두고, 처음부터 -4번째 전까지만 바꾼다. 바꿀부분은 별로 바꿀껀데, 그 갯수는 원래 핸드폰 길이에서 4개 적은 개수로 한다.

In [264]:
#다른 사람 코드

def hide_numbers(s):
    return "*"*(len(s)-4) + s[-4:]

8 크레인 인형뽑기 게임

### 1차시도 - 실패

In [265]:
import numpy as np

In [266]:
# board
# [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]

In [267]:
a=np.array([[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]])
a_trans = a.T

a

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 0, 3],
       [0, 2, 5, 0, 1],
       [4, 2, 4, 4, 2],
       [3, 5, 1, 3, 1]])

In [268]:
a_trans #전치행렬

array([[0, 0, 0, 4, 3],
       [0, 0, 2, 2, 5],
       [0, 1, 5, 4, 1],
       [0, 0, 0, 4, 3],
       [0, 3, 1, 2, 1]])

In [269]:
a_trans[0]

array([0, 0, 0, 4, 3])

In [270]:
a_trans[4]

array([0, 3, 1, 2, 1])

In [271]:
# def enter(moves):
#     for i in range(len(moves)):
#         h = k[i][0]
#         print(k[i])
#         print(h)
#     return

In [272]:
moves = [1,5,3,5,1,2,1,4] #a_trans 의 index 0,4,2,4,0,1,0,3 을 찾는다 

In [273]:
def 상준(move):
    a = []
    for i in range(len(move)):
        a.append(np.trim_zeros(a_trans[move[i]-1], trim='f')[0])
        # arr = np.delete(arr, 13) #사용한 변수를 지우는 작업을 해야하는데.ㅠ
    return a
        

In [274]:
# #함수를.. 만들 때... 변수명까지 같이 만들 수 있는가??!

# #생성할 변수 개수
# df_num=5

# #자동 변수 선언
# for i in range(1,df_num+1):
# 	globals()['df_{}'.format(i)]="hi~ df_{}".format(i)

# #선언 변수 출력
# for i in range(1,df_num+1):
# 	print(globals()['df_{}'.format(i)])

In [275]:
# i = 3
# moves[3]-1 #4
# a_trans[4] # array([0, 3, 1, 2, 1])
np.trim_zeros(([0, 3, 1, 2, 1]), trim='f') #[3, 1, 2, 1]
#원인을 찾았다.. 지워져야하는데.. 내 마음 속에서만 지웠구나..

[3, 1, 2, 1]

In [276]:
def ho():
    b = []
    for i in range(8):
        b.append(i)
    return b

ho()

# for i in range(10):
    # print(i)

[0, 1, 2, 3, 4, 5, 6, 7]

In [277]:
상준(moves)

[4, 3, 1, 3, 4, 2, 4, 4]

In [278]:
a_trans[상준(moves)]

array([[0, 3, 1, 2, 1],
       [0, 0, 0, 4, 3],
       [0, 0, 2, 2, 5],
       [0, 0, 0, 4, 3],
       [0, 3, 1, 2, 1],
       [0, 1, 5, 4, 1],
       [0, 3, 1, 2, 1],
       [0, 3, 1, 2, 1]])

In [279]:
# 배열의 13번째 값인 [70]을 삭제하기
# arr = np.delete(arr, 13) # axis 값을 입력하지 않아도 된다.
# arr

In [280]:
#moves [1,5,3,5,1,2,1,4]

In [281]:
a_trans_delete_0 = np.trim_zeros(a_trans[0], trim='f')
a_trans_delete_1 = np.trim_zeros(a_trans[1], trim='f')
a_trans_delete_2 = np.trim_zeros(a_trans[2], trim='f')
a_trans_delete_3 = np.trim_zeros(a_trans[3], trim='f')
a_trans_delete_4 = np.trim_zeros(a_trans[4], trim='f')

In [282]:
print(a_trans_delete_0)
print(a_trans_delete_1)
print(a_trans_delete_2)
print(a_trans_delete_3)
print(a_trans_delete_4) #결과값을 행렬로 다시 나타낼 수 있는가?

[4 3]
[2 2 5]
[1 5 4 1]
[4 3]
[3 1 2 1]


In [283]:
# np.concatenate((a_trans_delete_0,a_trans_delete_1),axis=2)

### 2차 시도

In [284]:
import numpy as np

In [285]:
# board
# [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]

# moves = [1,5,3,5,1,2,1,4] #a_trans 의 index 0,4,2,4,0,1,0,3 을 찾는다 

In [286]:
board =np.array([[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]])
board_trans = board.T

In [287]:
a_trans

array([[0, 0, 0, 4, 3],
       [0, 0, 2, 2, 5],
       [0, 1, 5, 4, 1],
       [0, 0, 0, 4, 3],
       [0, 3, 1, 2, 1]])

In [288]:
# doll_pull(a_trans[0])

In [289]:
# #3일차 완성작

# def 상준(move):
#     a = []
#     for i in range(len(move)):
#         c = a_trans[move[i]-1]
#         try:
#             # print(np.trim_zeros(c, trim='f')[0])
#             a.append(np.trim_zeros(c, trim='f')[0])
#             # print(a)
#         except IndexError:
#             pass
#         doll_pull(c)
#     return a


# 상준(moves)
# #오........ ㅠㅠㅠㅠㅠㅠ 거의 나와버렸다. ㅠㅠㅠㅠㅠㅠㅠㅠ
# #이제 중복만 제거하면 된다.. ㅠㅠ

In [290]:
# def doll_pull(c):
#     for i in range(len(c)):
#         if c[i] != 0:
#             answer = c[i]
#             c[i] = 0
#             # print(a_trans)
#             return(answer)
#         else:
#             pass

# #완벽하다.. 내가 원하는 함수를 만들었따.. ㅠㅠ

In [291]:
import numpy as np

def doll_pull(c): #뽑는 기계, c=기계가 뽑을 행
    for i in range(len(c)): #c를 차례로 돌며 값이 있나 확인
        if c[i] != 0: # c안의 값이 0이 아니라면,
            answer = c[i]  #인형을 복사해서 정답에 넣고,
            c[i] = 0 #복사된 인형은 삭제 (0으로 바꾸기)
            print(answer) #(삭제없는) 정답함 확인
            return(answer)
        else:     #c안의 값이 전부 0이라면..?
            pass  #그냥 넘어가


def solution(board, moves):
    board = np.array(board) #보드를 넘파이로
    b = board.T  #보드 전치
    a = []
    answer = 0
    for i in range(len(moves)): #moves 길이만큼 반복.. 뭘?
        c = b[moves[i]-1]  #moves에서 말하는 board 행 찾기
        try:
            t = np.trim_zeros(c, trim='f')[0] #행에서 앞자리 0 지우고, 가장 앞에 있는 숫자를 t라 하자 
            a.append(t)  # 리스트에 t값 추가
            if len(a) == 1: #막 추가된 값 하나 뿐이라면,
                pass #지나가
            elif a[-2] == a[-1]: #추가된 인형이 연속으로 같다면,
                del a[-1] 
                del a[-1]  #인형 두개 터뜨리고
                answer += 2 #답에 2 추가
            else: #막 시작한 것도 아니고, 인형이 연속으로 같지도 않으면
                pass #그냥 지나가
        except IndexError:  #np.trim_zero에서 빈행은 0으로 만들 수 없어 오류가 나면,
            pass            #그냥 지나가
        doll_pull(c) #인형뽑기
    return answer

In [292]:
# 상준(moves)

# index 0 is out of bounds for axis 0 with size 0

In [293]:
board = [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]

moves = [1,5,3,5,1,2,1,4] #a_trans 의 index 0,4,2,4,0,1,0,3 을 찾는다 

In [294]:
solution(board, moves) #켈켈켈켈켘ㄹ켈

4
3
1
1
3
2
4


4

9 약수의 합

In [295]:
# 23/01/11 pm 11:23 시작

In [296]:
# #for문에 i 이해하기

# n = 10
# for i in range(n):
#     print(i)

In [297]:
#1번 실패작

def solution(n):
    answer = 0
    for i in range(n):
        if n%i==0:
            answer += i
            print(answer)
    return answer



# n = 12
# solution(n)
# ZeroDivisionError: integer division or modulo by zero

In [298]:
#2번 실패작

def solution(n):
    answer = 0
    for i in range(n):
        if n%(i+1)==0:
            answer += i
            print(answer)
    return answer



# n = 12
# solution(n)
# 결과값 오류: answer에 i에 1 추가 안해줌

In [299]:
#완성작

def solution(n):
    answer = 0
    for i in range(n):
        if n%(i+1)==0:
            answer += (i+1)
            print(answer)
    return answer

# n = 12
# solution(n)

10 서울에서 김서방 찾기

In [300]:
seoul = ["Jane", "Kim"]
# return = "김서방은 1에 있다"
seoul.index('Kim')

1

In [301]:
def solution(seoul):
    김서방위치 = seoul.index('Kim')
    answer = '김서방은 {}에 있다'.format(김서방위치)
    return answer

In [302]:
solution(seoul)

'김서방은 1에 있다'

11 문자열 내 p와 y의 개수

>대문자와 소문자가 섞여있는 문자열 s가 주어집니다. s에 'p'의 개수와 'y'의 개수를 비교해 같으면 True, 다르면 False를 return 하는 solution를 완성하세요. 'p', 'y' 모두 하나도 없는 경우는 항상 True를 리턴합니다. 단, 개수를 비교할 때 대문자와 소문자는 구별하지 않습니다.

> 예를 들어 s가 "pPoooyY"면 true를 return하고 "Pyy"라면 false를 return합니다.

In [303]:
# s = "pPoooyY"
# answer = true

# s = "Pyy"
# answer = false

In [304]:
def solution(s):
    if (s.count('p') + s.count('P')) == (s.count('y') + s.count('Y')):
        answer = True
    else:
        answer = False
    return answer

In [305]:
s = "pPoooyY"
s.count('t') == s.count('c')


True

In [306]:
s = "pPoooyY"
s.count('c')

0

### 12 체육복

In [307]:
# s= [1,2,3]
# s.index(4)

# ValueError                                Traceback (most recent call last)

In [308]:
# def solution(n, lost, reserve):

    
        

    
    
#         체육복빌려주기(n, lost, reserve)
        
#     else:
#         def 체육복빌려주기(n, lost, reserve):
#             finally_lost = len(lost)
#             for i in range(len(lost)):
#                 try:
#                     if (reserve.index((lost[i])-1)): #잃어버린 친구 앞번호에 여유친구가 여유복이 있다면,
#                         reserve.remove(reserve.index((lost[i])-1)) #빌려준 여유복 없애고,
#                         finally_lost = finally_lost -1
#                 except ValueError:
#                     try:
#                         if (reserve.index((lost[i])+1)): #잃어버린 친구 뒷번호에 여유친구가 여유복이 있다면,
#                             reserve.remove(reserve.index((lost[i])+1)) #빌려준 여유복 없애고,
#                             finally_lost = finally_lost -1
#                     except ValueError:
#                         pass
#         print('finally_lost:{}'.format(finally_lost))        
#         return finally_lost

#     return n - finally_lost +1

In [309]:
#교집합 함수 만들기

def 교집합함수(n, lost, reserve):
    교집합 = list(set(lost).intersection(reserve))
    if 교집합 != []: #두 리스트의 교집합이 있다면,
        print('교집합:{}'.format(교집합))
        print('교집합의 개수 :{}개'.format(len(교집합)))
        for i in range(len(교집합)): #교집합의 수만큼 반복
            print('교집합 값 {} 제거'.format(교집합[i]))
            lost.remove(교집합[i])
            reserve.remove(교집합[i])
        print('lost:{}'.format(lost))
        print('reserve:{}'.format(reserve))


# n = 5
# lost = [1,2,3,4,5]
# reserve = [1,3,5]
# # 정답: 5

# print(lost)
# 교집합함수(n, lost, reserve)
# print(lost)


In [310]:
# #체육복 빌려주는 함수
# def 체육복빌려주기함수(n, lost, reserve):
#     finally_lost = len(lost)
#     print('finally_lost:{}'.format(finally_lost))
#     for i in range(len(lost)):
#         잃어버린친구번호 = lost[i]
#         잃어버린친구앞번호 = lost[i]-1
#         잃어버린친구뒷번호 = lost[i]+1
#         try:
#             print('잃어버린친구번호:{}'.format(잃어버린친구번호))
#             if 잃어버린친구앞번호 in reserve: #잃어버린 친구 앞번호에 여유친구가 여유복이 있다면,
#                 print('reserve:{}'.format(reserve))
#                 reserve.remove(잃어버린친구앞번호) #빌려준 여유복 없애고,
#                 print('reserve:{}'.format(reserve))
#                 finally_lost = finally_lost -1
#                 print('finally_lost:{}'.format(finally_lost))
#         except ValueError:
#             try:
#                 print('잃어버린친구번호:{}'.format(잃어버린친구번호))
#                 if 잃어버린친구뒷번호 in reserve: #잃어버린 친구 앞번호에 여유친구가 여유복이 있다면,
#                     reserve.remove(잃어버린친구뒷번호) #빌려준 여유복 없애고,
#                     finally_lost = finally_lost -1
#                     print('finally_lost?:{}'.format(finally_lost))
#             except ValueError:
#                 pass     
#     print('finally_lost!!:{}'.format(finally_lost))
#     return n-finally_lost

# n = 10
# lost = [2,4]
# reserve = [3,5]
# 체육복빌려주기함수(n, lost, reserve)

In [311]:
# n = 5
# lost = [4]
# reserve = [3]
# 체육복빌려주기함수(n, lost, reserve)

In [312]:
# #결합

# def solution(n,lost,reserve):
#     교집합함수(n, lost, reserve)
#     print(n,lost,reserve)
#     return 체육복빌려주기함수(n, lost, reserve)


# n = 10
# lost = [1,2,4]
# reserve = [1,3,5]
# solution(n,lost,reserve)


In [313]:
# b1 = [1,2,3,4,5,9,11,15]
# b2 = [3,4,6,7,8]
# b3 = list(set(b1).intersection(b2))
#교집합

In [314]:
# # n	lost	reserve	return
# # 5	[2, 4]	[1, 3, 5]	5
# # 5	[2, 4]	[3]	4
# # 3	[3]	[1]	2

# n = 5
# lost = [1,2,3,4,5]
# reserve = [1,3,5]
# # 정답: 5

# solution(n,lost,reserve)

In [315]:
# def 호호():
#     return 'gkgk'
# 호호()

In [316]:
# #오류발생
# a = [1]
# a.remove[1]
# # TypeError: 'builtin_function_or_method' object is not subscriptable

# #괄호가 대괄호가 아니라 소괄호다

In [317]:
# 리스트.remove(값)

체육복 2차 도전

In [318]:
# #교집합 함수 만들기

# def 교집합함수(n, lost, reserve):
#     교집합 = list(set(lost).intersection(reserve))
#     if 교집합 != []: #두 리스트의 교집합이 있다면,
#         print('교집합:{}'.format(교집합))
#         print('교집합의 개수 :{}개'.format(len(교집합)))
#         for i in range(len(교집합)): #교집합의 수만큼 반복
#             print('교집합 값 {} 제거'.format(교집합[i]))
#             lost.remove(교집합[i])
#             reserve.remove(교집합[i])
#         print('lost:{}'.format(lost))
#         print('reserve:{}'.format(reserve))
#     else:
#         print('교집함없음')


In [319]:
# # n	lost	reserve	return
# # 5	[2, 4]	[1, 3, 5]	5
# # 5	[2, 4]	[3]	4
# # 3	[3]	[1]	2

# n = 5
# lost = [1,2,3,4,5]
# reserve = [1,3,5]
# # 정답: 5

# solution(n,lost,reserve)

In [320]:

# n = 6
# lost = [1,2,4]
# reserve = [3,4,5]
# # 정답: 5

# # solution(n,lost,reserve)
# 교집합함수(n, lost, reserve)


In [321]:
def 여유치수줄이기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]-1
    print('치수줄인reserve:{}'.format(reserve)) #줄어든 여유분 체육복 치수

In [322]:
def 여유치수늘리기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]+2
    print('원상복귀 후 치수늘린 reserve:{}'.format(reserve)) #치수늘린 여유분 체육복 치수

In [323]:
n = 6
lost = [1,2,4]
reserve = [3,4,5]

def solution(n, lost, reserve):
    교집합함수(n, lost, reserve)
    여유치수줄이기(n,lost,reserve)
    교집합함수(n, lost, reserve)
    여유치수늘리기(n,lost,reserve)
    교집합함수(n, lost, reserve)
    return n-len(lost)

In [324]:
# solution(n, lost, reserve)

In [325]:
# 정의

def 교집합함수(n, lost, reserve):
    교집합 = list(set(lost).intersection(reserve))
    if 교집합 != []: #두 리스트의 교집합이 있다면,
        print('교집합:{}'.format(교집합))
        print('교집합의 개수 :{}개'.format(len(교집합)))
        for i in range(len(교집합)): #교집합의 수만큼 반복
            print('교집합 값 {} 제거'.format(교집합[i]))
            lost.remove(교집합[i])
            reserve.remove(교집합[i])
        print('lost:{}'.format(lost))
        print('reserve:{}'.format(reserve))
    else:
        print('교집함없음')


def 여유치수줄이기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]-1
    print('치수줄인reserve:{}'.format(reserve)) #줄어든 여유분 체육복 치수


def 여유치수늘리기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]+2
    print('원상복귀 후 치수늘린 reserve:{}'.format(reserve)) #치수늘린 여유분 체육복 치수


def solution(n, lost, reserve):
    교집합함수(n, lost, reserve)
    여유치수줄이기(n,lost,reserve)
    교집합함수(n, lost, reserve)
    여유치수늘리기(n,lost,reserve)
    교집합함수(n, lost, reserve)
    return n-len(lost)


In [326]:
# 정의

def 교집합함수(n, lost, reserve):
    교집합 = list(set(lost).intersection(reserve))
    if 교집합 != []:
        for i in range(len(교집합)):
            lost.remove(교집합[i])
            reserve.remove(교집합[i])



def 여유치수1줄이기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]-1




def 여유치수1늘리기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]+1



def 여유치수2줄이기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]-2




def 여유치수2늘리기(n,lost,reserve):
    for i in range(len(reserve)):
        reserve[i] = reserve[i]+2


def 늘리기먼저(a,b, c):
    교집합함수(a, b, c)
    여유치수1늘리기(a,b,c)
    교집합함수(a, b, c)
    여유치수2줄이기(a,b,c)
    교집합함수(a, b, c)
    return a-len(b)

def 줄이기먼저(d, e, f):
    교집합함수(d, e, f)
    여유치수1줄이기(d,e,f)
    교집합함수(d, e, f)
    여유치수2늘리기(d,e,f)
    교집합함수(d, e, f)
    return d-len(e)


def solution(n, lost, reserve):
    lost.sort()
    reserve.sort()
    try:
        if(1 in reserve):
            return 늘리기먼저(n, lost, reserve)
    except ValueError:
        pass
    return 줄이기먼저(n, lost, reserve)

In [327]:
# #테스트 17,18,19,20, 25 틀림

# n = 10
# lost = [2,4  ,   7,9]
# reserve = [1,3  ,  8,10]

# solution(n, lost, reserve)

# #현재 상황에서 체육복을 줄여버리면 0,2가 되고, 2를 먼저 빌려줘버리면, 
# # 나중에 늘려도 2만남아서.. 4번에게 빌려줄 수가 없음.
# # 물론 치수 늘린거 먼저해도 같은 문제가 충분히 발생할듯

# # 여유치수늘리기(n, lost, reserve)

In [328]:
# n = 10
# lost = [2,4]
# reserve = [3,5]

# solution(n, lost, reserve)

3차

In [329]:
# n = 10
# lost = [2,4  , 6,  7,9]
# reserve = [1,3  ,  8,10]

# # solution(n, lost, reserve)

In [330]:
def 교집합함수(n, lost, reserve):
    교집합 = list(set(lost).intersection(reserve))
    if 교집합 != []:
        for i in range(len(교집합)):
            lost.remove(교집합[i])
            reserve.remove(교집합[i])

In [331]:
# 교집합함수(n,lost,reserve)
# print(n,lost,reserve)

# # lost[0] = 2
# ori = 0
# for i in range(len(lost)):
#     if (lost[i]-1) in reserve:
#         print('yes') 
#         reserve.remove(lost[i]-1)
#         print(reserve)
#         ori += 1
#     elif (lost[i]+1) in reserve:
#         print('sure')
#         reserve.remove(lost[i]+1)
#         ori += 1
#     else:
#         print('not here')

# print(n,lost,reserve)
# print(ori)

In [332]:
# def 교집합함수(n, lost, reserve):
#     교집합 = list(set(lost).intersection(reserve))
#     if 교집합 != []:
#         for i in range(len(교집합)):
#             lost.remove(교집합[i])
#             reserve.remove(교집합[i])

# def solution(n,lost,reserve):
#     교집합함수(n,lost,reserve)
#     Salvation = 0
#     for i in range(len(lost)):
#         if (lost[i]-1) in reserve:
#             reserve.remove(lost[i]-1)
#             Salvation += 1
#         elif (lost[i]+1) in reserve:
#             reserve.remove(lost[i]+1)
#             Salvation += 1
#         else:
#             pass
#     return n-len(lost)+Salvation

In [333]:
#해결!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

def 교집합함수(n, lost, reserve):
    교집합 = list(set(lost).intersection(reserve))
    if 교집합 != []:
        for i in range(len(교집합)):
            lost.remove(교집합[i])
            reserve.remove(교집합[i])

def solution(n,lost,reserve):
    lost.sort()
    reserve.sort()
    교집합함수(n,lost,reserve)
    Salvation = 0
    for i in range(len(lost)):
        if (lost[i]-1) in reserve:
            reserve.remove(lost[i]-1)
            Salvation += 1
        elif (lost[i]+1) in reserve:
            reserve.remove(lost[i]+1)
            Salvation += 1
        else:
            pass
    return n-len(lost)+Salvation

In [334]:
n = 10
lost = [2,4  ,  7,9]
reserve = [1,3  ,  8,10]

solution(n,lost,reserve)

10

### 13 두 정수 사이의 합

In [ ]:
# 두 정수 a, b가 주어졌을 때 a와 b 사이에 속한 모든 정수의 합을 리턴하는 함수, solution을 완성하세요.
# 예를 들어 a = 3, b = 5인 경우, 3 + 4 + 5 = 12이므로 12를 리턴합니다.

In [335]:
#내 코드
def solution(a, b):
    if a<b:
        answer = (a+b)*(b-a+1)/2
    elif a>b:
        answer = (a+b)*(a-b+1)/2
    else:
        answer = a
    return answer

In [336]:
#다른사람 코드
def adder(a, b):
    if a > b: a, b = b, a
    return sum(range(a,b+1))

14 문자열 다루기 기본

In [ ]:
# 문자열 s의 길이가 4 혹은 6이고, 숫자로만 구성돼있는지 확인해주는 함수, solution을 완성하세요. 예를 들어 s가 "a234"이면 False를 리턴하고 "1234"라면 True를 리턴하면 됩니다.

In [3]:
# def solution(s):
#     if (len(s)==4 or len(s)==6):
#         try:
#             if int(s) ==0:
#                 answer = True
#             else: 
#                 anwer = False
#         except:
#             anwer = False
#     try:
#         if int(s):
#             if (len(s)==4 or len(s)==6):
#                 answer = True
#             else:
#                 answer = False
#         else:
#             answer = False
#     except:
#         answer = False
#     return answer

In [16]:
#문자열의 길이가 4 or 6인가요?
#문자가 숫자로만 되어있나요?
#그러면 합격!!!!


def solution(s):
    if len(s)==4 or len(s)==6:
        try:
            if type(int(s)) == int:
                answer = True
        except:
            answer = False
    else:
        answer = False
    return answer

In [21]:
s='0000'
solution(s)

True

In [20]:
#다른사람의 코드

def alpha_string46(s):
    try:
        int(s)
    except:
        return False
    return len(s) == 4 or len(s) == 6 