2 행렬의 덧셈

In [112]:
import numpy as np

def solution(arr1,arr2):
    return (np.array(arr1) + np.array(arr2)).tolist()



In [1]:
arr1 = [[1,2],[2,3]]
type(arr1)

list

In [113]:
# 첫 실수
# 함수 정의할 때 : 안씀.


# 두번째 실수
# np.array(리스트) 기억이 안남.. (np변환만 10번 넘게 검색한듯.. 이제는 기억할 때가 되지 않았는가)


# 세번째 실수
# 타입오류남. 오류코드는.....
# TypeError: Object of type ndarray is not JSON serializable
# 그대로 검색해보니 어레이.tolist() 붙이면 리스트로 변환 됨.

3 수박수박수박수박수박수?

In [2]:
def solution(n):
    몫 = n//2
    나머지 = n%2
    answer = ('수박')*몫 + ('수')*나머지
    return answer

In [4]:
solution(2000)

'수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수박수

4 완주하지 못한 선수

In [115]:
def solution(participant, completion):
    participant.sort()
    completion.sort()
    for i in range(len(completion)):
        if participant[i] == completion[i]:
            continue
        else:
            return participant[i]
    return participant[-1]

7 핸드폰 번호 가리기

In [116]:
#나의 코드

def solution(phone_number):
    return phone_number.replace(phone_number[:-4],'*'*(len(phone_number)-4))
    # 핸드폰번호를 대채하는데, 다른부분은 놔두고, 처음부터 -4번째 전까지만 바꾼다. 바꿀부분은 별로 바꿀껀데, 그 갯수는 원래 핸드폰 길이에서 4개 적은 개수로 한다.

In [117]:
#다른 사람 코드

def hide_numbers(s):
    return "*"*(len(s)-4) + s[-4:]

8 크레인 인형뽑기 게임

In [118]:
import numpy as np

행렬전환

In [119]:
# board
# [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]

In [120]:
a=np.array([[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]])
a_trans = a.T

a

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 0, 3],
       [0, 2, 5, 0, 1],
       [4, 2, 4, 4, 2],
       [3, 5, 1, 3, 1]])

In [121]:
a_trans

array([[0, 0, 0, 4, 3],
       [0, 0, 2, 2, 5],
       [0, 1, 5, 4, 1],
       [0, 0, 0, 4, 3],
       [0, 3, 1, 2, 1]])

In [122]:
a_trans[1]

array([0, 0, 2, 2, 5])

In [140]:
a_trans[0]

array([0, 0, 0, 4, 3])

In [149]:
k[1-1][0]

4

In [150]:
k[5-1][0]

3

In [161]:
def enter(moves):
    for i in range(len(moves)):
        h = k[i][0]
        print(k[i])
        print(h)
    return

In [152]:
moves = [1,5,3,5,1,2,1,4]

In [162]:
enter(moves)

[4 3]
4
[2 2 5]
2
[1 5 4 1]
1
[4 3]
4
[3 1 2 1]
3


IndexError: index 5 is out of bounds for axis 0 with size 5

In [139]:
#moves [1,5,3,5,1,2,1,4]

0 제거

In [138]:
def make_d(n):
    a_trans_delete_(n) = np.trim_zeros(a_trans[n], trim='f')


SyntaxError: cannot assign to function call (1920105763.py, line 2)

In [123]:
a_trans_delete_0 = np.trim_zeros(a_trans[0], trim='f')
a_trans_delete_1 = np.trim_zeros(a_trans[1], trim='f')
a_trans_delete_2 = np.trim_zeros(a_trans[2], trim='f')
a_trans_delete_3 = np.trim_zeros(a_trans[3], trim='f')
a_trans_delete_4 = np.trim_zeros(a_trans[4], trim='f')

In [124]:
print(a_trans_delete_0)
print(a_trans_delete_1)
print(a_trans_delete_2)
print(a_trans_delete_3)
print(a_trans_delete_4)

[4 3]
[2 2 5]
[1 5 4 1]
[4 3]
[3 1 2 1]


In [143]:
k=np.array([a_trans_delete_0,a_trans_delete_1,a_trans_delete_2,a_trans_delete_3,a_trans_delete_4])

C:\Users\prokj\AppData\Local\Temp\ipykernel_16952\172286821.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  k=np.array([a_trans_delete_0,a_trans_delete_1,a_trans_delete_2,a_trans_delete_3,a_trans_delete_4])


array change list. 

In [146]:
k[0][0]

4

In [125]:
type(a_trans_delete_0)

numpy.ndarray

In [136]:
a_trans_delete_0[0]

4

In [127]:
# moves
# [1,5,3,5,1,2,1,4]
# https://numpy.org/doc/stable/user/quickstart.html

떨거지

In [128]:
delete_0 = np.delete(a_trans[0],4)
delete_0

array([0, 0, 0, 4])

In [129]:
delete_0 = np.delete(a_trans[0],0)
delete_0

array([0, 0, 4, 3])

In [130]:
b = np.where(a_trans == 0,0,a_trans)

b
# where는 내가 찾는게 아닌듯

array([[0, 0, 0, 4, 3],
       [0, 0, 2, 2, 5],
       [0, 1, 5, 4, 1],
       [0, 0, 0, 4, 3],
       [0, 3, 1, 2, 1]])

In [131]:
len(a_trans[0])

5

In [132]:
c = np.delete(a_trans[0],0)
c

array([0, 0, 4, 3])

In [133]:
def delete_0():
    for i in range(5):
        if a_trans[0][0] == 0:
            c = np.delete(a_trans[0],0)
            print('2')
    else:
        return c

i really hate this situation.
i dont like him litterally.
i dont know why i hate so much. 
i think he doesn't respect me. 
so i will make document. document has power. i will borrow. 
i realized now. now is so late. but i will. i can.

In [134]:
delete_0()

2
2
2
2
2


array([0, 0, 4, 3])